# Generated by Django 3.2.12 on 2022-02-08 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('image', models.ImageField(upload_to='')),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=1000)),
                ('budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('coutnry', models.CharField(max_length=100)),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='spotlight.actor')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='spotlight.user')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('ethenicity', models.CharField(blank=True, max_length=100)),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='spotlight.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='spotlight.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('Actor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='spotlight.actor')),
                ('Movie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='spotlight.movie')),
                ('Role', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='spotlight.role')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='spotlight.user')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='spotlight.role'),
        ),
        migrations.AddField(
            model_name='actor',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='spotlight.user'),
        ),
    ]
