# Generated by Django 3.2.12 on 2022-02-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='category',
            field=models.CharField(choices=[('lead', 'lead'), ('extra', 'extra'), ('secondary', 'secondary'), ('stunt', 'stunt')], default='performer', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('performer', 'performer'), ('studio', 'studio')], default='performer', max_length=20),
        ),
    ]
