# Generated by Django 3.2.12 on 2022-02-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
