# Generated by Django 3.2.12 on 2022-02-10 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0003_auto_20220209_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='Movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='spotlight.movie'),
        ),
    ]
