# Generated by Django 3.2.12 on 2022-02-10 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0004_alter_role_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='Movie',
            new_name='movie',
        ),
    ]
