# Generated by Django 3.2.12 on 2022-02-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0007_auto_20220210_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='spotlight.actor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='spotlight.movie'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='spotlight.role'),
        ),
    ]
