# Generated by Django 3.2.12 on 2022-02-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0002_remove_user_type'),
        ('spotlight', '0008_auto_20220210_1430'),
    ]

    operations = [
    ]
