# Generated by Django 3.2.12 on 2022-02-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0009_merge_0002_remove_user_type_0008_auto_20220210_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('performer', 'performer'), ('studio', 'studio')], default='performer', max_length=20),
        ),
    ]
