# Generated by Django 3.2.12 on 2022-02-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0010_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='types',
        ),
    ]
